use anchor_lang::prelude::*;

#[error_code]
pub enum AnsemError {
    #[msg("Numeric overflow")] Overflow,
    #[msg("Block index out of range (0..25)")] BadBlock,
    #[msg("Round is not open")] RoundNotOpen,
    #[msg("Round deadline has not passed")] RoundNotEnded,
    #[msg("Round deadline has passed")] RoundEnded,
    #[msg("Round is not in the required state")] BadRoundState,
    #[msg("Stake below minimum")] StakeTooSmall,
    #[msg("Stake exceeds per-round maximum")] StakeTooLarge,
    #[msg("Insufficient escrow balance")] InsufficientBalance,
    #[msg("Must claim previous round before staking a new one")] UnclaimedRound,
    #[msg("Round already claimed by this player")] AlreadyClaimed,
    #[msg("Cannot withdraw with an active unclaimed round")] WithdrawLocked,
    #[msg("Swap mode mismatch")] WrongSwapMode,
    #[msg("Unauthorized")] Unauthorized,
    #[msg("MinerPosition round mismatch")] MinerRoundMismatch,
    #[msg("Pot vault lamports insufficient to cover escrow liabilities plus this round's pot")] Insolvent,
    #[msg("Previous round must be finalized (claimable or closed) before opening a new one")] PriorRoundNotSettled,
    #[msg("Round cannot be canceled (must be past deadline and in Open/Settled state)")] RoundNotCancelable,
    #[msg("Round is not closed")] RoundNotClosed,
    #[msg("No refundable stake for this player in this round")] NothingToRefund,
    #[msg("Round id is not the current round")] NotCurrentRound,
    #[msg("Escrow already joined to a round")] RoundAlreadyJoined,
    #[msg("Miner already reconciled for this round")] AlreadyReconciled,
    #[msg("Cannot commit a miner while its round is still open (staking not closed)")] CommitTooEarly,
    #[msg("Invalid return band (require min <= max <= RETURN_MAX_BPS)")] BadReturnBand,
    #[msg("Beef vault token account has wrong owner or mint")] BadBeefVault,
    #[msg("Invalid beef params (divisor and secs_per_tick must be > 0)")] BadBeefParams,
    #[msg("Swap proceeds below the configured min_swap_rate floor")] SwapRateTooLow,
    #[msg("Claim window still open — round not yet closeable")] ClaimWindowOpen,
    #[msg("Round is not in a closeable state")] RoundNotCloseable,
    #[msg("Invalid stake bounds (require 0 < min <= max)")] BadStakeBounds,
}
